### ISSUE TITLE
Cronjob

### ISSUE THREAD

**Issue by Fail-Unsafe** [mrlesmithjr/docker-phpipam#1]
root@919221a61a27:/# **whoami**
root
root@919221a61a27:/# **su -c whoami -s /bin/bash www-data**
www-data
root@919221a61a27:/# 

Would it be possible to modify the cron files so that the scripts will be executed as user www-data?

**Comment by Fail-Unsafe** [comment]
After a little more investigation, the problem seems to be that crond cannot access the environment variables for the database user and password. They are not available when crond executes the job.

**Comment by mrlesmithjr** [comment]
@Fail-Unsafe Thanks for filing this. I will look into this as soon as I have the chance. If you can provide as much detail that would be great.

**Comment by Fail-Unsafe** [comment]
I'm not that well versed in Docker so I'm not sure how exactly Docker passes in the environment variables. The cronjobs work e.g. when you modify config.php to use static values instead of getenv(...)

The cronjob probably has to look something like this

```
MYSQL_DB_HOSTNAME="mariadb"
MYSQL_DB_NAME="phpipam"
MYSQL_DB_PASSWORD="phpipam"
MYSQL_DB_PORT="3306"
MYSQL_DB_USERNAME="phpipam"  
*/15 * * * * /usr/local/bin/php /usr/local/www/phpipam/functions/scripts/pingCheck.php
```

We need a way to access those environment variables in a dynamic way.

**Comment by mrlesmithjr** [comment]
No worries at all. Thanks for the good info you already provided. Let me see what I can figure out. It has been quite a while since I have used this so it might take me some time.

**Comment by mrlesmithjr** [comment]
Did you build the `Docker` image from this repo or leverage the already built `Docker` image `mrlesmithjr/docker-phpipam`?

**Comment by Fail-Unsafe** [comment]
I use the mrlesmithjr/docker-phpipam image straight from Docker Hub.

**Comment by mrlesmithjr** [comment]
Awesome. And thanks!

**Comment by mrlesmithjr** [comment]
Another thought. Have you attempted my [docker-ansible-phpipam](https://github.com/mrlesmithjr/docker-ansible-phpipam) repo?

**Comment by Fail-Unsafe** [comment]
Not yet. I was looking for an image that already includes the necessary cronjobs. Is this an improved version of the other image?

**Comment by mrlesmithjr** [comment]
Yeah that image was one that was created after this repo. It does include the cronjobs as well so it might be worthwhile to test it out as well.

**Comment by Fail-Unsafe** [comment]
I did try your image but at first encountered a problem regarding our proxy. I've have passed in our proxy as an environment variable and then it worked.

Before that it was stuck at "apk update" and parts of the playbook.

Is there a way to change the interval of the cronjob? Maybe a possibility to pass in the interval as an environment variable through a jinja2 template?

 We have almost 100 subnets...the scanning takes too long for a 15min interval.

**Comment by mrlesmithjr** [comment]
Awesome! The current method of changing the cronjob would be by editing the [following](https://github.com/mrlesmithjr/docker-ansible-phpipam/blob/master/config/ansible/playbook.yml#L79-L110) `cron` tasks and then building the image from scratch. I can definitely look into the option of adding this as a passable variable for the longterm if that makes sense.

**Comment by Fail-Unsafe** [comment]
I forked your repo and tried to make the necessary modifications but failed. I moved the creation of the parameterized cronjobs from playbook.yml to phpipam-entrypoint.yml but when the container starts the playbook is never executed it seems.

**Comment by mrlesmithjr** [comment]
let's open up a discussion on https://github.com/mrlesmithjr/docker-ansible-phpipam and see if we can get this worked out for you.
