### ISSUE TITLE
This repo is highly deprecated...

### ISSUE THREAD

**Issue by inductor** [mrlesmithjr/docker-phpipam#3]
For those who's found this repo, I suggest yall use https://hub.docker.com/r/phpipam/phpipam-www instead of this repo because in this repo, the base image is debian jessie which is very old, and the PHP version is 5, which is already dead too...

**Comment by mrlesmithjr** [comment]
@inductor Man, this thing is definitely way out of date! Thanks for raising this. Much appreciated.
